/**
 * [ Supported Type ]
 *  : 지원하는 Type 종류와 Mapping 되는 Field
 */
const SUPPORTED_TYPES = {
    BOOLEAN     : 'BOOLEAN',
    CURRENCY    : 'CURRENCY',
    DATETIME    : 'DATETIME',
    DATE        : 'DATE',
    TIME        : 'TIME',
    EMAIL       : 'EMAIL',
    DOUBLE      : 'DOUBLE',
    LONG        : 'LONG',
    INTEGER     : 'INTEGER',
    PERCENT     : 'PERCENT',
    PHONE       : 'PHONE',
    REFERENCE   : 'REFERENCE',
    PICKLIST    : 'PICKLIST',
    STRING      : 'STRING'
    // ID          : 'ID',              // ID 는 input Field 로 수정불가..
};
/**
 * [ Operator ]
 *  : 전체 Operator 종류와 Field Type 별 지원하는 Operator
 */
const OPERATORS = {
    ANY_CHANGE              : { label : 'Any change',               value : 'Any change'},
    EQUALS                  : { label : 'Equals',                   value : 'Equals'},
    NOT_EQUALS              : { label : 'Not equal to',             value : 'Not equal to'},
    CONTAINS                : { label : 'Contains',                 value : 'Contains' },
    NOT_CONTAINS            : { label : 'Does not contain',         value : 'Does not contain'},
    GREATER_THAN            : { label : 'Greater than',             value : 'Greater than'},
    GREATER_THAN_OR_EQUAL   : { label : 'Greater than or Equal',    value : 'Greater than or Equal'},
    LESS_THAN               : { label : 'Less than',                value : 'Less than'},
    LESS_THAN_OR_EQUAL      : { label : 'Less than or Equal',       value : 'Less than or Equal'},
    EMPTY                   : { label : 'Empty',                    value : 'Empty'},
    NOT_EMPTY               : { label : 'Not empty',                value : 'Not empty'},
    START_WITH              : { label : 'Start with',               value : 'Start with'},
    END_WITH                : { label : 'End with',                 value : 'End with'}
};
// 필드 타입별 사용가능한 Operator
const COMPARE_OPERATOR = {
    SELF_COMPARE : {
        BOOLEAN     : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS],
        CURRENCY    : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        DATETIME    : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        DATE        : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        TIME        : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        EMAIL       : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY,OPERATORS.START_WITH,OPERATORS.END_WITH],
        DOUBLE      : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        LONG        : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        INTEGER     : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        PERCENT     : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        PHONE       : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY,OPERATORS.START_WITH,OPERATORS.END_WITH],
        REFERENCE   : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY],
        PICKLIST    : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.CONTAINS,OPERATORS.NOT_CONTAINS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY,OPERATORS.START_WITH,OPERATORS.END_WITH],
        STRING      : [OPERATORS.ANY_CHANGE,OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.CONTAINS,OPERATORS.NOT_CONTAINS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY,OPERATORS.START_WITH,OPERATORS.END_WITH]
    },
    OTHER_COMPARE : {
        BOOLEAN     : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS],
        CURRENCY    : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        DATETIME    : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        DATE        : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        TIME        : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        EMAIL       : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS],
        DOUBLE      : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        LONG        : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        INTEGER     : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        PERCENT     : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        PHONE       : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS],
        REFERENCE   : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS],
        PICKLIST    : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL],
        STRING      : [OPERATORS.EQUALS,OPERATORS.NOT_EQUALS,OPERATORS.GREATER_THAN,OPERATORS.GREATER_THAN_OR_EQUAL,OPERATORS.LESS_THAN,OPERATORS.LESS_THAN_OR_EQUAL]
    }
};
// 단독 수행되는 Operator
const STANDALONE_OPERATORS = [OPERATORS.ANY_CHANGE,OPERATORS.EMPTY,OPERATORS.NOT_EMPTY];


export { SUPPORTED_TYPES, COMPARE_OPERATOR, STANDALONE_OPERATORS }