/****************************************************************************************
  * @filename      : Account_tr_ts
  * @projectname   :
  * @author        : i2max_my.Seo
  * @date          : 2020-07-20 오후 1:53
  * @group         :
  * @group-content :
  * @description   : 
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author            description
  * ===============================================================
    0.1     2020-07-20 오후 1:53     i2max_my.Seo         Create
****************************************************************************************/
@IsTest
private class Account_tr_ts {
    @IsTest
    static void testBehavior() {
        TestDataBaseFactory.init();
        //TestDataBaseFactory.agencyAccount.DealerOwner__c = null;
        //update TestDataBaseFactory.agencyAccount;
    }
}