/****************************************************************************************
  * @filename      : LsMSalesAddGeneralMachineQa_ts
  * @projectname   :
  * @author        : i2max_my.Seo
  * @date          : 2020-07-15 오후 2:29
  * @group         :
  * @group-content :
  * @description   : 작업기 추가 신규 기능 -
  *                  작업기 전체 기준으로 필터 처리.
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author            description
  * ===============================================================
    0.1     2020-07-15 오후 2:29     i2max_my.Seo         Create
****************************************************************************************/
@IsTest
private class LsMSalesAddGeneralMachineQa_ts {
	@IsTest
	static void testBehavior() {
		LsMSalesAddGeneralMachineQa.runTest();
	}
}