/****************************************************************************************
  * @filename      : LsMSalesStepVO
  * @projectname   :
  * @author        : i2max
  * @date          : 2020-05-14
  * @group         :
  * @group-content :
  * @description   : [모바일] Step 업무의 VO Data Type
  *                : 모바일 Step 업무인 경우에는 반드시 implements 할 것
  *                : 리턴 데이터의 타입을 공통화하기 위함.
  * @tester        :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date            author         description
  * ===============================================================
    0.1     2020-05-14         i2max          Create
****************************************************************************************/
public interface LsMSalesStepVO {
}