/****************************************************************************************
  * @filename      : OrderNewQa_ts
  * @projectname   :
  * @author        : i2max_my.Seo
  * @date          : 2020-07-15 오전 9:17
  * @group         :
  * @group-content :
  * @description   :
  * @reference     :
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author            description
  * ===============================================================
    0.1     2020-07-15 오전 9:17     i2max_my.Seo         Create
****************************************************************************************/
@IsTest
private class OrderTransferPriceEditQa_ts {
	/**
	 * Test for NhGov.
	 */
	@IsTest
	static void testBehavior() {
		OrderTransferPriceEditQa.runTest();
	}

}